### ISSUE TITLE
--robust = 1 bring inflated result for rare variants? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [large-scale-gxe-methods/GEM#12]
Dear GEM team, 

I am wondering whether `--robust = 1` bring inflated result for rare variants compared with `--robust = 0`. Meanwhile,   `--robust = 1` always have more significant results compared with `--robust = 0`, correct? 

Thanks

Shicheng

**Comment by hanchenphd** [comment]
Hi Shicheng,

Thank you for your interest in GEM. I would not recommend using the robust standard errors for rare variants, because asymptotics depends on the minor allele count and may not work well for rare variants.

Best,
Han

**Comment by Shicheng-Guo** [comment]
Thank you Han!! It is consistent with what I noticed!! Thank you for your confirmation and Thank you for this great tool for GxE analysis!!
