### ISSUE TITLE
What does marginal genetic effect mean？

### ISSUE THREAD

**Issue by WZo0o** [large-scale-gxe-methods/GEM#15]
Dear GEM team,

Could you tell me the meaning of marginal genetic effect and the difference between marginal genetic effect and genetic main effect?

Thanks

**Comment by hanchenphd** [comment]
We use the term "marginal genetic effect" to denote the effect of a genetic variant in the absence of gene-environment interaction terms (i.e., in a regular GWAS). In contrast, genetic main effect in our model means the effect of a genetic variant in the presence of gene-environment interactions. Note that genetic main effect needs to be interpreted at specific E values (0 if E is not centered, and the mean of E if E is centered).

Han

**Comment by WZo0o** [comment]
Thanks for your reply.
