### ISSUE TITLE
How long will my data take?

### ISSUE THREAD

**Issue by riddhisera** [large-scale-gxe-methods/GEM#17]
Hi GEM team,

I have tried to use your software with a file having:
Number of variants: 156499
Number of samples: 348

GEM seems to get stuck after printing "Precalculations and fitting null model..." for more than 24hrs, it would be great if you could tell me how long I can expect it to run until it produces the results?

Device specifications:
Memory: 32 GiB
Processor: Intel® Core™ i7-9700 CPU @ 3.00GHz × 8

Thanks!
Riddhi

**Comment by pancong419** [comment]
The abnormal run time may be due to the collinearity of multiple covariates. Please use the latest version GEM1.4.5. We added a collinearity check of the covariates before fitting the null model.

**Comment by riddhisera** [comment]
Thank you so much, it works!
