### ISSUE TITLE
How to use GEM to mapping GxE related-QTLs with multiple years and multiple location observed results?

### ISSUE THREAD

**Issue by xiekunwhy** [large-scale-gxe-methods/GEM#5]
Hi,

For inbred plants, it is easy to get multi-environment trait trials results, for example, I have 3 years(2017, 2018, 2019) yield trait observed results of each inbred line in a mapping population. And how to use GEM to mapping GxE related-QTLs using these multi-environment observed results (with NGS genotyping results) ?

Best,
Kun

**Comment by kwesterman** [comment]
Hi Kun, can you please clarify what the exposures and outcomes are in this setup? It is straightforward to test GxE for multiple exposures jointly (generating a single p-value for interaction) by including multiple strings in the --exposure-names argument.  At the moment, GEM does not consider multiple phenotypes, so the outcomes for each year would have to be either included as independent observations or collapsed into a single aggregate value.

**Comment by xiekunwhy** [comment]
Hi @kwesterman ,

I don't known what are the exposures and outcomes, may be all are outcomes (one trait measured in different years).
And the phenotype table looks like following,
![image](https://user-images.githubusercontent.com/17738229/99744273-5b885880-2b12-11eb-938c-0c0a16075dc0.png)

Best,
Kun

**Comment by hanchenphd** [comment]
Hi Kun,

Thank you for your interest in GEM. I believe in your example, Yield-2017, Yield-2018 and Yield-2019 are correlated outcomes. If you were to include all of them in one analysis, you would need to specify their correlation structure. Unfortunately, the current version of GEM can only be applied to uncorrelated outcomes (e.g., Yield-2017, Yield-2018 and Yield-2019 in three separate analyses). You may have to use mixed-effects models or generalized estimating equations to handle correlated outcomes.

Best,
Han

> Hi @kwesterman ,
> 
> I don't known what are the exposures and outcomes, may be all are outcomes (one trait measured in different years).
> And the phenotype table looks like following,
> ![image](https://user-images.githubusercontent.com/17738229/99744273-5b885880-2b12-11eb-938c-0c0a16075dc0.png)
> 
> Best,
> Kun

**Comment by duytpm16** [comment]
Hi @xiekunwhy,

Do you still need help with this issue?

Thanks,
Duy

**Comment by xiekunwhy** [comment]
Hi,

Thank all of you, things have been done by comparing three years MLM gwas results.

Best,
Kun
